# -- GLOBAIS VAR --
TELA_LARGURA = 1280
TELA_ALTURA = 720
CHAO = 420

# CORES
AZUL = (0, 0, 255)
VERMELHO = (255, 0, 0)
AMARELO = (255, 255, 0)

# LARGURA x ALTURA PERSONAGEM
PER_LARGURA = 200
PER_ALTURA = 150

# ESTADOS E CHARS
PLAYER = "player"
INIMIGO = "inimigo"
ALIADO = "aliado"
DEROTA = "Fim de jogo"
VITORIA = "Vitória"
ESPERA = "Espera"
PAUSA = "Pausa"
JOGANDO = 'Jogando'
MENU= "Menu"
FIM = "Fim"

# BOTÕES
BOTAO_LARGURA = 200
BOTAO_ALTURA = 50
ESPACAMENTO = 20
MARGEM_INFERIOR = 30
